name: Release dist zip

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine tag name
        id: set_tag
        run: |
          TAG="${{ github.ref_name }}"
          if [ -z "$TAG" ]; then
            TAG="${{ github.event.release.tag_name }}"
          fi
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        run: npm run package

      - name: Copy zip with tag name
        run: cp graph-user-export-dist.zip "graph-user-export-dist-${{ steps.set_tag.outputs.tag_name }}.zip"

      - name: List files
        run: ls -la

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.set_tag.outputs.tag_name }}
          body: |
            Ladda ner den färdigbyggda appen här:

            - Senaste stabila länk (uppdateras automatiskt):
              https://github.com/${{ github.repository }}/releases/latest/download/graph-user-export-dist.zip
            - Denna release-fil (med versionsnummer):
              https://github.com/${{ github.repository }}/releases/download/${{ steps.set_tag.outputs.tag_name }}/graph-user-export-dist-${{ steps.set_tag.outputs.tag_name }}.zip

            Obs! "Source code (zip/tar.gz)" är auto-genererade och innehåller källkoden, inte den byggda appen.
          draft: false
          prerelease: false
          files: |
            graph-user-export-dist.zip
            graph-user-export-dist-${{ steps.set_tag.outputs.tag_name }}.zip
          fail_on_unmatched_files: true
          generate_release_notes: true
